### ISSUE TITLE
Change to dummy varibles

### ISSUE THREAD

**Issue by lineaba** [prog-o-meter/prog-o-meter#86]
__First timers only__

_This means that this issue have been determined a good place to start for someone who have not been contributing to open source before. Let us know how we can help you get started or if you have any questions. We would really love for you to join us_

There are certain places in the code where the variable i is used in the condition of a loop, but is not actually used in the body of the loop. (It is not all cases of i that is unused inside the body, the places where I is used inside the body, we would like to keep it as it is.)
We want to change these variables to the dummy variable (the underscore character), to improve readability of our code. 

If you want to read more about the issue and our reason for changing it, check out these past conversation in #52 (note that the line number is probably no longer 130, but a simple search for i, should help you find the places where it is used) and #56 

As always, please let us know if you have any questions :)

**Comment by omkar2810** [comment]
Can I work on this issue,just want to get the taste of contributing with this task.

**Comment by lineaba** [comment]
Hey @omkar2810 ThadeuJose have already solved this issue, but since I haven't merged it yet, if you just want to try it out, you can clone the repo and try it out on your own. 
You can also just clone our repo and walk through it and see if you understand what the code does. If there a places where it is unclear what the code does, it would be useful if you would tell me where, cause then I know we need to work more on documentation on those places.
